/*******************************************************************************
 * Copyright IBM Corp. and others 2024
 *
 * This program and the accompanying materials are made available under
 * the terms of the Eclipse Public License 2.0 which accompanies this
 * distribution and is available at https://www.eclipse.org/legal/epl-2.0/
 * or the Apache License, Version 2.0 which accompanies this distribution
 * and is available at https://www.apache.org/licenses/LICENSE-2.0.
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the
 * Eclipse Public License, v. 2.0 are satisfied: GNU General Public License,
 * version 2 with the GNU Classpath Exception [1] and GNU General Public
 * License, version 2 with the OpenJDK Assembly Exception [2].
 *
 * [1] https://www.gnu.org/software/classpath/license.html
 * [2] https://openjdk.org/legal/assembly-exception.html
 *
 * SPDX-License-Identifier: EPL-2.0 OR Apache-2.0 OR GPL-2.0-only WITH Classpath-exception-2.0 OR GPL-2.0-only WITH OpenJDK-assembly-exception-1.0
 *******************************************************************************/

#include "gtest/gtest.h"
#include "ilgen/IlInjector.hpp"
#include "ilgen/IlGeneratorMethodDetails_inlines.hpp"
#include "ilgen/MethodInfo.hpp"
#include "ilgen/TypeDictionary.hpp"
#include "TestDriver.hpp"

namespace TestCompiler
{

/**
 * Simple IL Injector that generates: return param1 * param2
 * 
 * This test demonstrates DIRECT CODEGEN TESTING without any optimization passes.
 * It verifies that the imul evaluator correctly generates machine code for
 * integer multiplication.
 */
class SimpleMultiplyIlInjector : public TR::IlInjector
   {
   public:
   TR_ALLOC(TR_Memory::IlGenerator)

   SimpleMultiplyIlInjector(TR::TypeDictionary *types, TestDriver *test)
      : TR::IlInjector(types, test)
      {
      }

   bool injectIL()
      {
      createBlocks(1);
      
      // Generate IL: return parameter(0) * parameter(1);
      // This creates an 'imul' IL node that will be directly translated
      // to machine code by the code generator (evaluator)
      returnValue(
         createWithoutSymRef(TR::imul, 2,
            parameter(0, Int32),
            parameter(1, Int32)));
      
      return true;
      }
   };

/**
 * Method info describing the signature: int32_t multiply(int32_t a, int32_t b)
 */
class SimpleMultiplyInfo : public TestCompiler::MethodInfo
   {
   public:
   SimpleMultiplyInfo(TestDriver *test)
      : _ilInjector(&_types, test)
      {
      TR::IlType* Int32 = _types.PrimitiveType(TR::Int32);
      _args[0] = Int32;
      _args[1] = Int32;
      DefineFunction(__FILE__, LINETOSTR(__LINE__), "simpleMultiply", 2, _args, Int32);
      DefineILInjector(&_ilInjector);
      }

   typedef int32_t (*MethodType)(int32_t, int32_t);

   private:
   TR::TypeDictionary _types;
   TestCompiler::SimpleMultiplyIlInjector _ilInjector;
   TR::IlType *_args[2];
   };

/**
 * Test driver for simple multiplication test.
 * 
 * IMPORTANT: This extends TestDriver (NOT OptTestDriver), which means:
 * - NO optimization passes are run
 * - The IL is directly compiled to machine code
 * - This tests the codegen (imul evaluator) in isolation
 */
class SimpleMultiplyTest : public TestDriver
   {
   public:
   void invokeTests()
      {
      // Get the compiled native code entry point
      auto testMethod = getCompiledMethod<SimpleMultiplyInfo::MethodType>();
      
      // Execute the generated machine code and verify results
      // Each call executes the native instructions generated by codegen
      ASSERT_EQ(6, testMethod(2, 3));
      ASSERT_EQ(0, testMethod(0, 5));
      ASSERT_EQ(0, testMethod(7, 0));
      ASSERT_EQ(6, testMethod(-2, -3));
      ASSERT_EQ(-10, testMethod(5, -2));
      ASSERT_EQ(-10, testMethod(-5, 2));
      ASSERT_EQ(100, testMethod(10, 10));
      ASSERT_EQ(1000000, testMethod(1000, 1000));
      }
   };

/**
 * The actual test case.
 * 
 * This test:
 * 1. Generates IL with an imul opcode
 * 2. Compiles directly to native code (NO optimizations)
 * 3. Executes the native code
 * 4. Verifies the multiplication results are correct
 * 
 * If the imul evaluator (codegen) has bugs, these assertions will fail.
 */
TEST_F(SimpleMultiplyTest, DirectCodegenTest)
   {
   SimpleMultiplyInfo info(this);
   setMethodInfo(&info);
   
   // RunTest() compiles and invokes without any optimization passes
   RunTest();
   }

} // namespace TestCompiler
